version: '3.5'

services:

  gui:
    container_name: gui
    build:
      context: ./gui
      dockerfile: Dockerfile
    volumes:
      - ./gui:/usr/src/gui
      - /usr/src/gui/node_modules
    ports:
      - 80:3000
    environment:
      NODE_ENV: development
      VIRTUAL_HOST: '*/*'
      VIRTUAL_HOST_WEIGHT: 0


  backend:
    image: backend
    build: ./backend
    command: python app.py
    ports:
      - 80
    environment:
      VIRTUAL_HOST: '*/backend, */backend/*'
      VIRTUAL_HOST_WEIGHT: 10

  db:
    container_name: mongo
    image: mongo:latest
    volumes:
      - data:/run/db
    ports:
      - 27017:27017

  lb:
    image: dockercloud/haproxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 80
    links:
      - db
      - backend
      - gui

volumes:
  data:
