version: '3.5'

services:

  gui:
    container_name: gui
    build:
      context: ./gui
      dockerfile: Dockerfile
    volumes:
      - './gui:/usr/src/gui'
      - '/usr/src/gui/node_modules'
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development
