version: "3"

services:

  gui:
    image: gui
    build: ./gui
    ports:
      - 80
    environment:
      VIRTUAL_HOST: "*/*"

  lb:
    image: dockercloud/haproxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - '80:80'
      - '1936:1936'
    links:
      - gui

volumes:
    database-storage:
